# Generated by Django 6.0.1 on 2026-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('unidade', models.FloatField()),
                ('gas_nh3', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
