# Generated by Django 6.0.1 on 2026-01-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='unidade',
            new_name='umidade',
        ),
    ]
