# Generated by Django 6.0.1 on 2026-01-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_rename_unidade_sensordata_umidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AC', 'Ar-condicionado'), ('OUTRO', 'Outro')], max_length=20)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
