# Generated by Django 6.0.1 on 2026-01-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_empresa_perfil_sensor_unidade_delete_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='gas_nh3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temperatura',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='umidade',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
