# Generated by Django 6.0.1 on 2026-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_sensor_gas_nh3_sensor_temperatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='tipo',
            new_name='tipo_sensor',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='endereco',
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_instalacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
