# Generated by Django 6.0.1 on 2026-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_rename_tipo_sensor_tipo_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, default='Não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('Gestor', 'Administrador (Full Access)'), ('Técnico', 'Técnico (Manutenção/Sensores)'), ('Operador', 'Operador (Vizualização/Uso Geral)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(default='Geral', max_length=50),
        ),
    ]
