# Generated by Django 6.0.1 on 2026-01-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0007_alter_empresa_endereco_alter_perfil_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('gestor', 'Gestor (Administrador - Full Access)'), ('tecnico', 'Técnico (Manutenção/Sensores)'), ('operador', 'Operador (Visualização/Uso Geral)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
