# Generated by Django 6.0.1 on 2026-01-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0008_alter_perfil_cargo_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa_logos/'),
        ),
    ]
