# Generated by Django 6.0.1 on 2026-01-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0009_empresa_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensores'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.unidade'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='monitoramento.empresa'),
        ),
    ]
