# Generated by Django 6.0.1 on 2026-01-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0010_alter_perfil_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('gestor', 'Gestor (Administrador - Full Access)'), ('tecnico', 'Técnico (Manutenção/Sensores)'), ('operador', 'Operador (Visualização/Uso Geral)')], default='operador', max_length=20),
        ),
    ]
